### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 

# this project was upgraded form Spring Boot 1.5 and some attribute names had to be updated. See:
# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Configuration-Changelog

spring.jmx:
   enabled: false

server:
  port: 8090

# run management (actuator) endpoints on a separate port
management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: '*'    #by default this would be health,info

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-example
  version: 0.7
  description: boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

hotel.service:
  name: 'default profile:'
---
spring:
  profiles: test
  h2:
    console:
      enabled: true

spring.jpa:
    hibernate.ddl-auto: create-drop

hotel.service:
  name: 'test profile:'
  
logging:
  file: boot_example.log
  org.hibernate: INFO

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE

amazon:
  dynamodb.endpoint: http://localhost:8000/
  aws:
    accesskey=put_access_key_here
    secretkey=put_secret_key_here


 